### PR TITLE
Laravel 10 compatability

### PR DESCRIPTION
**Pull request by schmeits**
I updated the composer.json so the package can be used in Laravel 10 applications

### CODE REVIEW

**Comment by mitulgolakiya** [comment]
@schmeits I am running a bit busy this week. Have you tested it after a change in composer.json? Everything working fine?

**Comment by schmeits** [comment]
Hi there, yes did try it out and it works. But still figuring out if it’s suitable for my use-case 😊

Van: Mitul Golakiya ***@***.***>
Verzonden: donderdag 6 april 2023 11:45
Aan: InfyOmLabs/laravel-calendar-events ***@***.***>
CC: Schmeits websolutions | Tally Schmeits ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [InfyOmLabs/laravel-calendar-events] Laravel 10 compatability (PR #12)


@schmeits<https://github.com/schmeits> I am running a bit busy this week. Have you tested it after a change in composer.json? Everything working fine?

**Comment by BryanPlaces** [comment]
Hi @mitulgolakiya , Can you update the code? I updated my project to laravel 10 and I have the compatibility problem

Thanks a lot

**Comment by mitulgolakiya** [comment]
@BryanPlaces It's merged. @schmeits Thank you for the contribution.

**Pull request merged**
